### ISSUE TITLE
Please put on stackage

### ISSUE THREAD

**Issue by kvanbere** [tsani/servant-github-webhook#3]
& configure so it doesn't require this to work with stackage:
```
# Override default flag values for local packages and extra-deps
flags: {
  servant-github-webhook: {old-base: false}
}
```

:-)

**Comment by tsani** [comment]
My PR to stackage just got merged. servant-github-webhook should appear in the next nightly!

**Comment by kvanbere** [comment]
This is working a treat now, thanks!

Working integration of this + github-webhooks [here](https://github.com/onrock-eng/github-webhooks/tree/master/examples/servant).
