### ISSUE TITLE
Depends on non-existent github-webhooks package

### ISSUE THREAD

**Issue by snoyberg** [tsani/servant-github-webhook#9]
The dependency seems to have been added in 0.4, but the package does not exist on Hackage, making the package impossible to build.

**Comment by tsani** [comment]
Thanks for reporting this; I didn't realize `github-webhooks` was not yet on Hackage. I've gotten in touch with the maintainer and it should be uploaded some time in the near future. When it is I'll open a PR to stackage to update the `build-constraints.yaml`.

**Comment by kvanbere** [comment]
@snoyberg sorry about this one.

**Comment by snoyberg** [comment]
No worries :)

**Comment by kvanbere** [comment]
@snoyberg after https://github.com/tsani/servant-github-webhook/pull/10 lands (which depends on https://github.com/fpco/stackage/pull/3322 landing) this should no longer be an issue. Sorry for the delay in addressing this downstream.

**Comment by tsani** [comment]
Now that the relevant PRs have landed, this is resolved: servant-github-webhook builds with stackage nightly without extra-deps. I'm waiting on fpco/stackage#3331 to be merged to close this issue.

**Comment by tsani** [comment]
servant-github-webhook 0.4.0.0 is now live on stackage nightly
